string nome, especie, pelecor, raca;
int idade;
Console.WriteLine("petpet pet");
Console.WriteLine("Qual o nome do animal:");
nome = Console.ReadLine()!;
Console.WriteLine("Qual o especie do animal:");
especie = Console.ReadLine()!;
Console.WriteLine("Qual a raça do animal:");
raca = Console.ReadLine()!;
Console.WriteLine("Qual a pelaem/cor do animal:");
pelecor = Console.ReadLine()!;
Console.WriteLine("Qual a idade do animal:");
idade = Convert.ToInt32(Console.ReadLine()!);
Console.WriteLine ("========================================");
Console.WriteLine("|Pet Hotel: Petotel|".PadLeft(31, '_').PadRight(40, '_'));
Console.WriteLine ("========================================");
Console.Write ($"|Espécie:{especie}|".PadRight(20, '.'));
Console.WriteLine ($"|Raça:{raca}|".PadLeft(20, '.'));
Console.WriteLine ("========================================");
Console.WriteLine ($"Atende pelo nome de: {nome}");
Console.Write ($"|Idade:{idade}|".PadRight(20, '.'));
Console.WriteLine ($"|Pelaem/Cor:{pelecor}|".PadLeft(20, '.'));
Console.WriteLine ("========================================");
